### ISSUE TITLE
Why call moment with UTC timestamp?

### ISSUE THREAD

**Issue by hughlilly** [fourseven/nziff-calendar#1]
Lines 62 & 63 call moment.js thus: `moment(begin).utc()…`

Why UTC? I think this is why events come into calendars (or at least my iCal) as GMT...

**Comment by fourseven** [comment]
Hey @hughlilly - `moment.js` is a 3rd party library, so the logic issue will be with `script.js` somewhere. I'm having a look now, oddly ical worked for me :-1:

**Comment by fourseven** [comment]
Oh you're talking about `ics.js` - yes that needs to be in UTC, your calendar should covert it across for you, what are you loading it into? Mac Calendar?

**Comment by hughlilly** [comment]
Yeah Mac Calendar… It doesn’t seem to convert from UTC. Events come in in
GMT!

**Comment by fourseven** [comment]
Ah okay. I've just updated the code, can you clone the repo and then load it in chrome and try please? Instructions to load custom extensions from a folder are here - https://developer.chrome.com/extensions/getstarted#unpacked - just delete the old version.

**Comment by hughlilly** [comment]
Yes that works! Woohoo! Also, I just taught myself how to use GitHub and how to load an unpacked extension 👌🏻

**Comment by fourseven** [comment]
Great job, I'll do a v2.1 release tomorrow then!

Mathew Hartley
